apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: [YOUR-AWS-ACCOUNT-ID].dkr.ecr.[REGION].amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Seneca@123"
    - name: MYSQL_DATABASE
      value: "employees"