apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  imagepullSecrets:
  - name: ecr-secret
  containers:
  - name: mysql
    image: 166147787843.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Seneca@123"
    - name: MYSQL_DATABASE
      value: "employees"